# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\Documents\Balraje G\qt designer using Application\win_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 464)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_click = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_click.setGeometry(QtCore.QRect(190, 330, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_click.setFont(font)
        self.pushButton_click.setStyleSheet("\n"
"background-color: rgb(96, 133, 255);\n"
"color:rgb(255,255,255)")
        self.pushButton_click.setObjectName("pushButton_click")
        self.click_count_label = QtWidgets.QLabel(self.centralwidget)
        self.click_count_label.setGeometry(QtCore.QRect(150, 200, 251, 61))
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.click_count_label.setFont(font)
        self.click_count_label.setObjectName("click_count_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_click.setText(_translate("MainWindow", "Click Me"))
        self.click_count_label.setText(_translate("MainWindow", "Number Of Clicks :-  "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
